version: 2.1

commands:
  npm_install_if_necessary:
    steps:
      - restore_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
      - run:
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          paths:
            - node_modules
          key: v1-node_modules-{{ checksum "package-lock.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - npm_install_if_necessary
      - run: npm run test
      - run: npm run coverage
      - run: npx codecov
